Add forms
Apatakiti/Blog_rails pull request #7
Opened 2023-12-08 19:54 UTC by Ademola-coding

## Project requirements

- Create a method called current_user in your ApplicationController to make current user data available to all controllers.

    -   It will return the first user from the database.

- Don't worry about proper authentication at this time. You will add it in the upcoming projects.

    - Create forms to perform the following functions:
    - Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
    - Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).

- Allow Users to add likes to Posts.

2023-12-08 20:08 UTC, rloterh commented
Hi @Ademola-coding 

Can you make your ReadMe look more professional
- Let's remove the logo from ReadMe
- Add Future Features section
- Remove placeholder or instruction text at the License section

Let's do this asap. Cheers

2023-12-08 20:55 UTC, rloterh requested changes
Hi Rite, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 
🏁 🌴 🚦 🚗 🏫 🏡 _🏃

## Highlights 👍  
- Good jobs o far on form creation!
- Good ReadMe

## Required Changes ♻️
_Kindly check the inline comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-08 20:55 UTC, rloterh commented on app/views/posts/show.html.erb
> +</section>
- [x] The form for adding a new post is displaying correctly, however, an attempt to add a sample post is throwing an error. Let's endeavor to improve upon the same:

**Error thrown whiles saving a post:**
![image](https://github.com/Ademola-coding/Blog_rails/assets/12745474/655ae1ea-f5b3-4da9-8ea3-d86efc374bad)
a new

2023-12-09 20:19 UTC, abdulhamiid approved these changes
# 🟢 Approved! 🥳 
Hi @Ademola-coding 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use preprocessed HTML files with embedded Ruby code.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-22 13:34 UTC, merged